CREATE TABLE `Account` (
    `ACCOUNT_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ACCOUNT_FULLNAME` VARCHAR(100) NOT NULL,
    `ACCOUNT_USERNAME` VARCHAR(50) NOT NULL UNIQUE,
    `ACCOUNT_EMAIL` VARCHAR(100) NOT NULL UNIQUE,
    `ACCOUNT_PASSWORD` VARCHAR(255) NOT NULL,
    `ACCOUNT_PHONE` VARCHAR(15),
    `ACCOUNT_AVATAR` VARCHAR(255),
    `ACCOUNT_ROLE` ENUM('Admin','User') NOT NULL DEFAULT 'User',
    `ACCOUNT_STATUS` ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
    `ACCOUNT_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE `RoomType` (
    `ROOMTYPE_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ROOMTYPE_NAME` VARCHAR(100) NOT NULL,
    `ROOMTYPE_PRICE_PER_NIGHT` DECIMAL(10,2) NOT NULL,
    `ROOMTYPE_DISCOUNT_PERCENTAGE` INT DEFAULT 0,
    `ROOMTYPE_DESCRIPTION` TEXT,
    `ROOMTYPE_THUMBNAIL` VARCHAR(255),
    `ROOMTYPE_MAX_GUESTS` INT NOT NULL DEFAULT 2,
    `ROOMTYPE_BED_TYPE` ENUM( 'singleBed', 'doubleBed', 'queenBed', 'kingBed' ) NOT NULL DEFAULT 'singleBed';
    `ROOMTYPE_STATUS` ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
    `ROOMTYPE_SLUG` VARCHAR(255) NOT NULL UNIQUE,
    `ROOMTYPE_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `Room` (
    `ROOM_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ROOM_NUMBER` VARCHAR(20) NOT NULL UNIQUE,
    `ROOM_ROOMTYPE_ID` INT NOT NULL,
    `ROOM_DESCRIPTION` TEXT,
    `ROOM_STATUS` ENUM(
        'Available',
        'Booked',
        'Occupied',
        'Maintenance'
    ) DEFAULT 'Available',
    `ROOM_SLUG` VARCHAR(255) NOT NULL UNIQUE,
    `ROOM_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT `FK_ROOM_ROOMTYPE`
        FOREIGN KEY (`ROOM_ROOMTYPE_ID`)
        REFERENCES `RoomType`(`ROOMTYPE_ID`)
);

CREATE TABLE Booking (
    BOOKING_ID INT AUTO_INCREMENT PRIMARY KEY,
    BOOKING_ROOM_ID INT NOT NULL,
    BOOKING_ACCOUNT_ID INT NOT NULL,
    BOOKING_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    BOOKING_CHECKIN DATE NOT NULL,
    BOOKING_CHECKOUT DATE NOT NULL,
    BOOKING_TOTAL_PRICE DECIMAL(10,2) NOT NULL,
    BOOKING_NOTES TEXT,
    PAYMENT_METHOD ENUM('Cash', 'Bank Transfer') NOT NULL DEFAULT 'Cash',
    BOOKING_STATUS ENUM('Pending', 'Confirmed', 'Cancelled', 'Completed') NOT NULL DEFAULT 'Pending',

    CONSTRAINT FK_BOOKING_ROOM
        FOREIGN KEY (BOOKING_ROOM_ID)
        REFERENCES Room(ROOM_ID),

    CONSTRAINT FK_BOOKING_ACCOUNT
        FOREIGN KEY (BOOKING_ACCOUNT_ID)
        REFERENCES Account(ACCOUNT_ID)
);